In [1]:
import numpy as np

In [2]:
arr= [[ 0.9526, -0.246 , -0.8856],[ 0.5639, 0.2379, 0.9104]]
data = np.array(arr)
print(data)

[[ 0.9526 -0.246  -0.8856]
 [ 0.5639  0.2379  0.9104]]


In [3]:
data*10 # nhân từng phần tử với 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [4]:
data+data # cộng từng phần tử với chính nó

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [5]:
data.shape # kiểm tra kích thước của ma trận

(2, 3)

In [6]:
data.dtype # kiểm tra kiểu dữ liệu của ma trận

dtype('float64')

In [7]:
data1 = [6, 7.5, 8, 0, 1] 
arr1 = np.array(data1) # tạo mảng từ list
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2) # tạo mảng 2 chiều từ list
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim # kiểm tra số chiều của mảng

2

In [10]:
arr2.shape # kiểm tra kích thước của mảng

(2, 4)

In [11]:
arr1.dtype, arr2.dtype # kiểm tra kiểu dữ liệu của mảng

(dtype('float64'), dtype('int64'))

In [12]:
np.zeros(10) # tạo mảng 1 chiều 10 phần tử có giá trị bằng 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,6)) # tạo mảng 2 chiều 3x6 có giá trị bằng 0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.empty((2,3,2)) # tạo mảng 3 chiều 2x3x2 có giá trị bằng 0

array([[[4.68767236e-310, 0.00000000e+000],
        [1.03977794e-312, 9.54898106e-313],
        [1.16709769e-312, 1.01855798e-312]],

       [[1.23075756e-312, 1.03977794e-312],
        [1.01855798e-312, 9.76118064e-313],
        [1.06099790e-312, 1.90979621e-312]]])

In [15]:
np.arange(15) # tạo mảng 1 chiều có giá trị từ 0 đến 14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # tạo mảng 1 chiều có kiểu dữ liệu là float64
arr2 = np.array([1, 2, 3], dtype=np.int32) # tạo mảng 1 chiều có kiểu dữ liệu là int32
arr1.dtype, arr2.dtype


(dtype('float64'), dtype('int32'))

In [17]:
arr = np.array([1, 2, 3, 4, 5]) # tạo mảng 1 chiều
arr.dtype 


dtype('int64')

In [18]:
float_arr = arr.astype(np.float64) # ép kiểu dữ liệu của mảng arr thành float64
float_arr.dtype

dtype('float64')

In [19]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [20]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_) # tạo mảng 1 chiều có kiểu dữ liệu là string
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [21]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype) # ép kiểu dữ liệu của mảng int_array thành kiểu dữ liệu của mảng calibers

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
empty_uint32 = np.empty(8, dtype='u4') # tạo mảng 1 chiều có kiểu dữ liệu là unsigned int 32
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [23]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
arr*arr # nhân từng phần tử với chính nó

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [25]:
arr-arr # trừ từng phần tử với chính nó

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
1/arr # chia 1 cho từng phần tử

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [27]:
arr**0.5 # lấy căn bậc 2 của từng phần tử

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
arr = np.arange(10) # tạo mảng 1 chiều có giá trị từ 0 đến 9
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[5] # truy cập phần tử thứ 5 của mảng

5

In [30]:
arr[5:8] # truy cập phần tử từ thứ 5 đến thứ 7 của mảng

array([5, 6, 7])

In [31]:
arr[5:8]=12 # gán giá trị 12 cho các phần tử từ thứ 5 đến thứ 7 của mảng
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
arr_slice = arr[5:8] # lấy mảng con từ mảng arr từ phần tử thứ 5 đến thứ 7
arr_slice

array([12, 12, 12])

In [33]:
arr_slice[1]=12345 # gán giá trị 12345 cho phần tử thứ 2 của mảng arr_slice
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [34]:
arr_slice[:]=64 # gán giá trị 64 cho các phần tử của mảng arr_slice
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [35]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # tạo mảng 2 chiều 3x3
arr2d[2]

array([7, 8, 9])

In [36]:
arr2d[0][2] # truy cập phần tử thứ 3 của hàng thứ 1 của mảng arr2d

3

In [37]:
arr2d[0,2] # truy cập phần tử thứ 3 của hàng thứ 1 của mảng arr2d

3

In [38]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # tạo mảng 3 chiều 2x2x3
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
arr3d[0] # truy cập mảng con thứ 1 của mảng arr3d

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
old_values = arr3d[0].copy() # sao chép mảng con thứ 1 của mảng arr3d
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d[0] = old_values # gán lại giá trị cho mảng con thứ 1 của mảng arr3d
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arr3d[1, 0] # truy cập phần tử thứ 1 của hàng thứ 2 của mảng arr3d

array([7, 8, 9])

In [43]:
arr[1:6] # truy cập các phần tử từ thứ 2 đến thứ 6 của mảng arr

array([ 1,  2,  3,  4, 64])

In [44]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr2d[:2] # truy cập các phần tử của hàng thứ 1 và thứ 2 của mảng arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr2d[:2, 1:] # truy cập các phần tử của hàng thứ 1 và thứ 2 của mảng arr2d từ cột thứ 2 đến cột cuối cùng

array([[2, 3],
       [5, 6]])

In [47]:
arr2d[1, :2] # truy cập các phần tử của hàng thứ 2 của mảng arr2d từ cột thứ 1 đến cột thứ 2

array([4, 5])

In [48]:
arr2d[2, :1] # truy cập các phần tử của hàng thứ 3 của mảng arr2d từ cột thứ 1 đến cột thứ 1

array([7])

In [49]:
arr2d[:,:1] # truy cập các phần tử của hàng thứ 1,2,3 của mảng arr2d từ cột thứ 1 đến cột thứ 1

array([[1],
       [4],
       [7]])

In [50]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) # tạo mảng chứa tên
data = np.random.randn(7, 4) # tạo mảng 2 chiều 7x4 với các giá trị ngẫu nhiên
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [51]:
data

array([[-0.62181775, -0.32076753, -0.06164881, -0.15466555],
       [ 0.79103531,  1.23257626, -0.200215  , -0.97475035],
       [ 1.69575346,  0.57430585,  1.5931783 , -0.10090605],
       [-0.38357871, -0.0592452 , -0.71776525,  0.05174742],
       [ 3.02537213, -1.22397265,  0.08796126,  0.76921996],
       [-0.45857013, -0.20665538, -0.21399147,  1.61749198],
       [ 3.09713957, -0.15903029,  1.47551467, -0.28266924]])

In [52]:
names == 'Bob' # trả về mảng các giá trị True/False tương ứng với các phần tử của mảng names

array([ True, False, False,  True, False, False, False])

In [53]:
data[names == 'Bob'] # truy cập các phần tử của mảng data có tên là Bob

array([[-0.62181775, -0.32076753, -0.06164881, -0.15466555],
       [-0.38357871, -0.0592452 , -0.71776525,  0.05174742]])

In [54]:
data[names == 'Bob', 2:] # truy cập các phần tử của mảng data có tên là Bob từ cột thứ 3 đến cột cuối cùng

array([[-0.06164881, -0.15466555],
       [-0.71776525,  0.05174742]])

In [55]:
data[names == 'Bob', 3] # truy cập các phần tử của mảng data có tên là Bob từ cột thứ 4 đến cột thứ 4

array([-0.15466555,  0.05174742])

In [56]:
names != 'Bob' # trả về mảng các giá trị True/False tương ứng với các phần tử của mảng names

array([False,  True,  True, False,  True,  True,  True])

In [57]:
data[~(names == 'Bob')] # truy cập các phần tử của mảng data không có tên là Bob

array([[ 0.79103531,  1.23257626, -0.200215  , -0.97475035],
       [ 1.69575346,  0.57430585,  1.5931783 , -0.10090605],
       [ 3.02537213, -1.22397265,  0.08796126,  0.76921996],
       [-0.45857013, -0.20665538, -0.21399147,  1.61749198],
       [ 3.09713957, -0.15903029,  1.47551467, -0.28266924]])

In [58]:
mask = (names == 'Bob') | (names == 'Will') # tạo mảng các giá trị True/False tương ứng với các phần tử của mảng names
mask

array([ True, False,  True,  True,  True, False, False])

In [59]:
data[mask] # truy cập các phần tử của mảng data có tên là Bob hoặc Will

array([[-0.62181775, -0.32076753, -0.06164881, -0.15466555],
       [ 1.69575346,  0.57430585,  1.5931783 , -0.10090605],
       [-0.38357871, -0.0592452 , -0.71776525,  0.05174742],
       [ 3.02537213, -1.22397265,  0.08796126,  0.76921996]])

In [60]:
data[data < 0] = 0 # gán giá trị 0 cho các phần tử có giá trị âm của mảng data
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.79103531, 1.23257626, 0.        , 0.        ],
       [1.69575346, 0.57430585, 1.5931783 , 0.        ],
       [0.        , 0.        , 0.        , 0.05174742],
       [3.02537213, 0.        , 0.08796126, 0.76921996],
       [0.        , 0.        , 0.        , 1.61749198],
       [3.09713957, 0.        , 1.47551467, 0.        ]])

In [61]:
data[names != 'Joe'] = 7 # gán giá trị 7 cho các phần tử có tên khác Joe của mảng data
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.79103531, 1.23257626, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 1.61749198],
       [3.09713957, 0.        , 1.47551467, 0.        ]])

In [62]:
arr = np.empty((8, 4)) # tạo mảng 2 chiều 8x4 với các giá trị ngẫu nhiên
for i in range(8): # vòng lặp từ 0 đến 7
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [63]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [64]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [65]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [66]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # truy cập các phần tử của mảng arr có chỉ số hàng là 1, 5, 7, 2 và chỉ số cột là 0, 3, 1, 2


array([ 4, 23, 29, 10])

In [67]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] # truy cập các phần tử của hàng thứ 2,6,8,3 của mảng arr từ cột thứ 1,4,2,3

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [68]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])] # truy cập các phần tử của hàng thứ 2,6,8,3 của mảng arr từ cột thứ 1,4,2,3

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [69]:
arr = np.arange(15).reshape((3, 5)) # tạo mảng 2 chiều 3x5
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
arr.T # chuyển vị của mảng arr

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [71]:
arr = np.random.randn(6, 3) # tạo mảng 2 chiều 6x3 với các giá trị ngẫu nhiên
np.dot(arr.T, arr) # tích vô hướng của hai mảng arr.T và arr

array([[ 4.76633393, -1.1088938 ,  0.85576714],
       [-1.1088938 ,  3.59095003, -2.82517191],
       [ 0.85576714, -2.82517191,  3.27683068]])

In [72]:
arr = np.arange(16).reshape((2, 2, 4)) # tạo mảng 3 chiều 2x2x4
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [73]:
arr.transpose((1, 0, 2)) # chuyển vị của mảng arr

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [74]:
arr.swapaxes(1, 2) # hoán vị hai trục của mảng arr

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [75]:
arr = np.arange(10) # tạo mảng 1 chiều 10 phần tử
np.sqrt(arr) # tính căn bậc hai của các phần tử của mảng arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [76]:
np.exp(arr) # tính e mũ các phần tử của mảng arr

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [77]:
x = np.random.randn(8) # tạo mảng 1 chiều 8 phần tử với các giá trị ngẫu nhiên
y = np.random.randn(8) # tạo mảng 1 chiều 8 phần tử với các giá trị ngẫu nhiên
x

array([-0.97935362, -0.43158574,  0.10997037, -2.95146671,  2.21663109,
       -0.6070551 , -0.01300373,  0.57928275])

In [78]:
y

array([-1.08442593e-03, -8.95809954e-01, -1.21283306e+00,  1.53418384e+00,
       -1.35518560e+00, -1.74049005e+00,  1.43712608e-01, -6.79060675e-02])

In [79]:
np.maximum(x, y) # trả về mảng các phần tử lớn nhất của hai mảng x và y

array([-1.08442593e-03, -4.31585743e-01,  1.09970365e-01,  1.53418384e+00,
        2.21663109e+00, -6.07055095e-01,  1.43712608e-01,  5.79282751e-01])

In [80]:
arr = np.random.randn(7) * 5 # tạo mảng 1 chiều 7 phần tử với các giá trị ngẫu nhiên
np.modf(arr)

(array([ 0.03256658, -0.62098419,  0.96531105,  0.50979131, -0.77647908,
         0.96462409, -0.12230393]),
 array([ 9., -0.,  4.,  4., -3.,  3., -0.]))

In [81]:
points = np.arange(-5, 5, 0.01) # tạo mảng 1 chiều các giá trị từ -5 đến 5 với bước nhảy 0.01
xs , ys = np.meshgrid(points, points)  # tạo mảng 2 chiềz các giá trị từ -5 đến 5 với bước nhảy 0.01
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [82]:
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)  # tính căn bậc hai của tổng bình phương của hai mảng xs và ys
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [1]:
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar() # vẽ đồ thị màu của mảng z
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values") # đặt tiêu đề cho đồ thị
plt.show()

NameError: name 'plt' is not defined

In [84]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) 
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y)
            for x, y, c in zip(xarr, yarr, cond)] # tạo mảng 1 chiều từ mảng xarr, yarr và cond
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [85]:
result = np.where(cond, xarr, yarr) # tạo mảng 1 chiều từ mảng xarr, yarr và cond
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [86]:
arr = np.random.randn(4, 4) # tạo mảng 2 chiều 4x4 với các giá trị ngẫu nhiên
arr

array([[-0.81261377, -0.02445536,  0.10292803, -0.66749041],
       [ 0.44065094, -0.37190257, -1.62378942, -0.55518086],
       [-0.28810328,  2.64479603,  1.27174493,  0.42563542],
       [ 0.02655512,  1.29982194,  0.86633067, -0.53257542]])

In [87]:
np.where(arr > 0, 2, -2) # tạo mảng 2 chiều 4x4 với các giá trị 2 nếu các phần tử của mảng arr lớn hơn 0, ngược lại là -2

array([[-2, -2,  2, -2],
       [ 2, -2, -2, -2],
       [-2,  2,  2,  2],
       [ 2,  2,  2, -2]])

In [88]:
np.where(arr > 0, 2, arr) # tạo mảng 2 chiều 4x4 với các giá trị 2 nếu các phần tử của mảng arr lớn hơn 0, ngược lại là các phần tử của mảng arr

array([[-0.81261377, -0.02445536,  2.        , -0.66749041],
       [ 2.        , -0.37190257, -1.62378942, -0.55518086],
       [-0.28810328,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.53257542]])

In [89]:
arr = np.random.randn(5, 4) # tạo mảng 2 chiều 5x4 với các giá trị ngẫu nhiên
arr.mean() # tính giá trị trung bình của mảng arr

-0.019199971135661187

In [90]:
np.mean(arr) # tính giá trị trung bình của mảng arr

-0.019199971135661187

In [91]:
arr.sum() # tính tổng các phần tử của mảng arr

-0.38399942271322374

In [92]:
arr.mean(axis=1) # tính giá trị trung bình của các phần tử của mảng arr theo trục 1

array([-0.18570214, -0.40681144,  0.05345656, -0.25528474,  0.6983419 ])

In [93]:
arr.sum(0) # tính tổng các phần tử của mảng arr theo trục 0

array([-1.71730136, -3.08070751,  2.40421402,  2.00979542])

In [94]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]]) # tạo mảng 2 chiều 3x3
arr.cumsum(0) # tính tổng tích lũy các phần tử của mảng arr theo trục 0

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [95]:
arr.cumprod(1) # tính tích tích lũy các phần tử của mảng arr theo trục 1

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [96]:
arr = np.random.randn(100) # tạo mảng 1 chiều 100 phần tử với các giá trị ngẫu nhiên
(arr > 0).sum() # đếm số lượng các phần tử của mảng arr lớn hơn 0

54

In [97]:
bools = np.array([False, False, True, False]) 
bools.any() # kiểm tra xem có phần tử nào của mảng bools là True không

True

In [98]:
bools.all() # kiểm tra xem tất cả các phần tử của mảng bools có phải là True không

False

In [99]:
arr = np.random.randn(8) 
arr

array([ 0.54381524, -2.04533473, -0.65746311,  0.91664067,  0.57226991,
       -0.15491926,  0.53467265,  0.64612697])

In [100]:
arr.sort() # sắp xếp các phần tử của mảng arr theo thứ tự tăng dần
arr

array([-2.04533473, -0.65746311, -0.15491926,  0.53467265,  0.54381524,
        0.57226991,  0.64612697,  0.91664067])

In [101]:
arr = np.random.randn(5, 3) 
arr


array([[-0.42838869,  0.83045954,  0.09501064],
       [ 0.29216265,  0.55195908,  0.613116  ],
       [ 3.13389072, -0.22125128,  0.12890908],
       [-1.03765886, -1.78633216,  1.32140506],
       [ 1.05110026, -1.11356762, -0.36865986]])

In [102]:
arr.sort(1) # sắp xếp các phần tử của mảng arr theo thứ tự tăng dần theo trục 1
arr

array([[-0.42838869,  0.09501064,  0.83045954],
       [ 0.29216265,  0.55195908,  0.613116  ],
       [-0.22125128,  0.12890908,  3.13389072],
       [-1.78633216, -1.03765886,  1.32140506],
       [-1.11356762, -0.36865986,  1.05110026]])

In [2]:
large_arr = np.random.randn(1000) 
large_arr.sort() 
large_arr[int(0.05 * len(large_arr))] # lấy phần tử thứ 5% của mảng large_arr


NameError: name 'np' is not defined

In [104]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names) # lấy các giá trị duy nhất của mảng names
 

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [105]:
ints   = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints) # lấy các giá trị duy nhất của mảng ints

array([1, 2, 3, 4])

In [106]:
sorted(set(names)) # lấy các giá trị duy nhất của mảng names

['Bob', 'Joe', 'Will']

In [107]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6]) # kiểm tra xem các phần tử của mảng values có nằm trong mảng [2, 3, 6] không


array([ True, False, False,  True,  True, False,  True])

In [108]:
arr = np.arange(10) 
np.save('some_array', arr) # lưu mảng arr vào file some_array.npy
np.load('some_array.npy') # đọc mảng từ file some_array.npy


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.savez('array_archive.npz', a=arr, b=arr) # lưu mảng arr vào file array_archive.npz

In [110]:
arch = np.load('array_archive.npz') # đọc mảng từ file array_archive.npz
arch['b'] # truy xuất mảng b trong file array_archive.npz

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
arr = np.loadtxt('array_ex.txt', delimiter=',') # đọc mảng từ file array_ex.txt
arr

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.670238, -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])

In [112]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x,y

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 6., 23.],
        [-1.,  7.],
        [ 8.,  9.]]))

In [114]:
x.dot(y) # tính tích của 2 ma trận x và y

array([[ 28.,  64.],
       [ 67., 181.]])

In [115]:
np.dot(x, np.ones(3)) # tính tích của ma trận x và ma trận 1 chiều 3 phần tử

array([ 6., 15.])

In [116]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5) 
mat = X.T.dot(X)    # tính tích của ma trận X.T và ma trận X
inv(mat)           # tính nghịch đảo của ma trận mat

array([[ 1.98441612, -0.30538233,  0.3213768 , -1.13500072,  0.50354254],
       [-0.30538233,  2.09505732,  0.26230833,  0.42411394,  1.28174139],
       [ 0.3213768 ,  0.26230833,  0.2586231 , -0.07865143,  0.29886485],
       [-1.13500072,  0.42411394, -0.07865143,  0.92019785, -0.26520843],
       [ 0.50354254,  1.28174139,  0.29886485, -0.26520843,  1.28677849]])

In [117]:
mat.dot(inv(mat)) # tính tích của ma trận mat và ma trận nghịch đảo của ma trận mat

array([[ 1.00000000e+00, -4.21800328e-16, -1.47850682e-16,
         6.55673119e-16,  5.90612758e-16],
       [-6.10466610e-16,  1.00000000e+00, -2.34705776e-18,
         1.70727843e-16,  7.19851114e-17],
       [-5.20219122e-16,  9.51239275e-16,  1.00000000e+00,
        -3.73187714e-17, -1.02307407e-15],
       [ 3.48816827e-16,  2.91708695e-16,  8.70692745e-17,
         1.00000000e+00,  2.70967582e-16],
       [-5.84004584e-17, -2.95326736e-17, -1.04961305e-16,
         9.55615943e-17,  1.00000000e+00]])

In [118]:
q,r = qr(mat) # tính ma trận Q và ma trận R của ma trận mat
r

array([[-5.10999884,  3.61558144,  8.20836096, -9.59810279, -5.57912069],
       [ 0.        , -5.79090954, -0.49444644,  4.95880256,  7.45069103],
       [ 0.        ,  0.        , -4.64529888, -0.52363257,  1.13757372],
       [ 0.        ,  0.        ,  0.        , -0.66195264, -0.11355088],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.51904329]])

In [119]:
samples = np.random.normal(size=(4, 4)) # tạo mảng 2 chiều 4x4 với các giá trị ngẫu nhiên
samples

array([[ 0.4416582 , -0.67721306, -1.12164293,  0.14506908],
       [ 0.13317256, -0.06957514, -0.08174455,  0.53442333],
       [-2.26738826, -1.38011516,  1.387209  ,  0.36112886],
       [-0.22434366, -0.08450783, -0.10705803, -0.14296594]])

In [122]:
from random import normalvariate
N = 10000
%timeit samples = [normalvariate(0, 1) for _ in range(N)] # thời gian thực hiện vòng lặp

25 ms ± 3.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [123]:

%timeit np.random.normal(size=N) # thời gian thực hiện vòng lặp

940 µs ± 29.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [125]:
import random
position = 0
walk = [position] # khởi tạo mảng walk với phần tử đầu tiên là 0
steps = 1000
for i in range(steps):
 step = 1 if random.randint(0, 1) else -1   # tạo ra một bước đi ngẫu nhiên
 position += step # cập nhật lại vị trí
 walk.append(position) # thêm vị trí mới vào mảng walk

In [127]:
nsteps = 1000 
draws = np.random.randint(0, 2, size=nsteps) # tạo mảng 1 chiều 1000 phần tử với các giá trị ngẫu nhiên là 0 hoặc 1
steps = np.where(draws > 0, 1, -1) # tạo mảng 1 chiều 1000 phần tử với các giá trị là 1 hoặc -1
walk = steps.cumsum() # tính tổng tích lũy của các phần tử của mảng steps
walk.min(), walk.max() # tìm giá trị nhỏ nhất và lớn nhất của mảng walk

(-15, 40)

In [128]:
(np.abs(walk) >= 10).argmax() # tìm vị trí của phần tử đầu tiên trong mảng walk có giá trị tuyệt đối lớn hơn hoặc bằng 10

19

In [129]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # tạo mảng 2 chiều 5000x1000 với các giá trị ngẫu nhiên là 0 hoặc 1
steps = np.where(draws > 0, 1, -1) # tạo mảng 2 chiều 5000x1000 với các giá trị là 1 hoặc -1
walks = steps.cumsum(1) # tính tổng tích lũy của các phần tử của mảng steps theo chiều dọc
walks 

array([[ -1,   0,  -1, ...,  -2,  -3,  -2],
       [ -1,   0,  -1, ...,  22,  21,  22],
       [  1,   0,  -1, ...,  -4,  -5,  -6],
       ...,
       [  1,   2,   3, ...,   2,   1,   0],
       [  1,   0,  -1, ..., -36, -35, -36],
       [ -1,  -2,  -1, ..., -56, -57, -56]])

In [130]:
walks.max(), walks.min()

(108, -110)

In [131]:
hits30 = (np.abs(walks) >= 30).any(1) # tìm các phần tử có giá trị tuyệt đối lớn hơn hoặc bằng 30
hits30

array([False,  True, False, ..., False,  True,  True])

In [132]:
hits30.sum()  # đếm số lượng phần tử có giá trị tuyệt đối lớn hơn hoặc bằng 30

3380

In [133]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1) # tìm vị trí của phần tử đầu tiên trong mảng walks có giá trị tuyệt đối lớn hơn hoặc bằng 30
crossing_times.mean()

500.93668639053254