# # Bài 2: Viết hàm hồi quy đơn biến bậc 1 và bậc 2 như sau


In [1]:
import numpy as np
from scipy import linalg

In [2]:
def mean(x): 
    sum = 0
    for i in range(len(x)): 
        sum += x[i]
    mean = sum / len(x)
    return mean

In [3]:
def sum(data):
    sum = 0
    for value in data: 
        sum += value
    return sum

In [4]:
data = np.array([[1,2,3,4,5],
        [6,7,8,9,10]])

In [5]:
print(data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
sum(data[1])
print(data[0]**2)
print(mean(data[0])) 
print(data[0] - mean(data[0]))

[ 1  4  9 16 25]
3.0
[-2. -1.  0.  1.  2.]


In [21]:
def regression(data, type): 
    n = len(data[0])
    if type == 1:
        beta1_hat = sum((data[0] - mean(data[0])) * (data[1] - mean(data[1]))) / sum((data[0] - mean(data[0])) ** 2)
        beta0_hat = ((1 / n) * sum(data[1])) - ((1 / n) * (sum(data[0]) *beta1_hat))
        return [beta0_hat,beta1_hat]
    if type == 2: 
        sum1 = sum(data[0])
        sum2 = sum(data[0] ** 2) 
        sum3 = sum(data[0] ** 3)
        sum4 = sum(data[0] ** 4) 
        sum5 = sum(data[1]) 
        sum6 = sum(data[0] * data[1]) 
        sum7 = sum((data[0] ** 2) * data[1])
        A = np.array([[1, sum1, sum2],
                      [sum1, sum2, sum3],
                      [sum2, sum3, sum4]])
        B = np.array([[sum5], [sum6], [sum7]])
        result = linalg.solve(A,B) 
        return result

In [22]:
print(regression(data, 1))

[5.0, 1.0]


In [23]:
np.array([1,2,3])**2

array([1, 4, 9])